<a href="https://colab.research.google.com/github/2303A51040/python-ds_1040/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#1
import pandas as pd

# Create two sample datasets
students = pd.DataFrame({
    'student_id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'class': ['A', 'A', 'B', 'B', 'C']
})

scores = pd.DataFrame({
    'student_id': [1, 2, 3, 5, 6],
    'exam_score': [85, 90, 78, 92, 88]
})

print("Students Dataset:\n", students, "\n")
print("Scores Dataset:\n", scores, "\n")

# --- Merging ---
inner_merge = pd.merge(students, scores, on='student_id', how='inner')
left_merge = pd.merge(students, scores, on='student_id', how='left')
right_merge = pd.merge(students, scores, on='student_id', how='right')

print("Inner Merge:\n", inner_merge, "\n")
print("Left Merge:\n", left_merge, "\n")
print("Right Merge:\n", right_merge, "\n")

# --- Aggregate Statistics ---
print("Aggregate Statistics:")
print("Mean Score:", inner_merge['exam_score'].mean())
print("Max Score:", inner_merge['exam_score'].max())
print("Min Score:", inner_merge['exam_score'].min())
print("Count of Scores:", inner_merge['exam_score'].count())

# --- Group By Example (class-wise average score) ---
group_stats = inner_merge.groupby('class')['exam_score'].agg(['mean', 'max', 'min', 'count'])
print("\nClass-wise Statistics:\n", group_stats)

Students Dataset:
    student_id     name class
0           1    Alice     A
1           2      Bob     A
2           3  Charlie     B
3           4    David     B
4           5      Eva     C

Scores Dataset:
    student_id  exam_score
0           1          85
1           2          90
2           3          78
3           5          92
4           6          88

Inner Merge:
    student_id     name class  exam_score
0           1    Alice     A          85
1           2      Bob     A          90
2           3  Charlie     B          78
3           5      Eva     C          92

Left Merge:
    student_id     name class  exam_score
0           1    Alice     A        85.0
1           2      Bob     A        90.0
2           3  Charlie     B        78.0
3           4    David     B         NaN
4           5      Eva     C        92.0

Right Merge:
    student_id     name class  exam_score
0           1    Alice     A          85
1           2      Bob     A          90
2           3  Charlie     B          78
3           5      Eva     C          92
4           6      NaN   NaN          88

Aggregate Statistics:
Mean Score: 86.25
Max Score: 92
Min Score: 78
Count of Scores: 4

Class-wise Statistics:
        mean  max  min  count
class
A      87.5   90   85      2
B      78.0   78   78      1
C      92.0   92   92      1

In [2]:
# 2
customers = pd.DataFrame({
    'customer_id': [101, 102, 103, 104, 105],
    'customer_name': ['John', 'Sara', 'Mike', 'Linda', 'Tom'],
    'region': ['North', 'South', 'East', 'West', 'North']
})

sales = pd.DataFrame({
    'sale_id': [1, 2, 3, 4, 5, 6, 7],
    'customer_id': [101, 102, 101, 103, 105, 105, 106],
    'amount': [200, 150, 300, 400, 250, 500, 100]
})

print("Customers Dataset:\n", customers, "\n")
print("Sales Dataset:\n", sales, "\n")

# --- Merge ---
inner_merge_sales = pd.merge(customers, sales, on='customer_id', how='inner')
left_merge_sales = pd.merge(customers, sales, on='customer_id', how='left')

print("Inner Merge (customers with sales):\n", inner_merge_sales, "\n")
print("Left Merge (all customers, sales may be NaN):\n", left_merge_sales, "\n")

# --- Aggregate Sales Statistics ---
print("Total Sales:", inner_merge_sales['amount'].sum())
print("Average Sales:", inner_merge_sales['amount'].mean())
print("Max Sale:", inner_merge_sales['amount'].max())
print("Sales Count:", inner_merge_sales['amount'].count())

# --- Per Customer Statistics ---
customer_sales = inner_merge_sales.groupby('customer_name')['amount'].sum()
print("\nSales per Customer:\n", customer_sales)

# --- Group by Region ---
region_sales = inner_merge_sales.groupby('region')['amount'].agg(['sum', 'mean', 'max', 'count'])
print("\nSales by Region:\n", region_sales)

Customers Dataset:
    customer_id customer_name region
0          101          John  North
1          102          Sara  South
2          103          Mike   East
3          104         Linda   West
4          105           Tom  North

Sales Dataset:
    sale_id  customer_id  amount
0        1          101     200
1        2          102     150
2        3          101     300
3        4          103     400
4        5          105     250
5        6          105     500
6        7          106     100

Inner Merge (customers with sales):
    customer_id customer_name region  sale_id  amount
0          101          John  North        1     200
1          101          John  North        3     300
2          102          Sara  South        2     150
3          103          Mike   East        4     400
4          105           Tom  North        5     250
5          105           Tom  North        6     500

Left Merge (all customers, sales may be NaN):
    customer_id customer_name region  sale_id  amount
0          101          John  North      1.0   200.0
1          101          John  North      3.0   300.0
2          102          Sara  South      2.0   150.0
3          103          Mike   East      4.0   400.0
4          104         Linda   West      NaN     NaN
5          105           Tom  North      5.0   250.0
6          105           Tom  North      6.0   500.0

Total Sales: 1800
Average Sales: 300.0
Max Sale: 500
Sales Count: 6

Sales per Customer:
 customer_name
John    500
Mike    400
Sara    150
Tom     750
Name: amount, dtype: int64

Sales by Region:
          sum   mean  max  count
region
East     400  400.0  400      1
North   1250  312.5  500      4
South    150  150.0  150      1